#!/bin/sh

poweroff()   { sudo poweroff        ;}
restart()    { killall -HUP dwm     ;}
reboot()     { sudo reboot          ;}
lock()       { bosskey              ;}

func="$(declare -F | awk '{print $3}' | dmenu -i -p "Powermenu:")"
[ -z "$func" ] || "$func"
