#!/bin/sh

vol="$(pamixer --get-volume)"

if [ $(pamixer --get-mute) = true ]; then
	icon=""
elif [ "$vol" -ge "50" ]; then
	icon=""
elif [ "$vol" -gt "0" ]; then
	icon=""
elif [ "$vol" -eq "0" ]; then
	icon=""
fi

echo "$icon $vol%"
